language: ruby
rvm:
  - 2.3.1
services:
  - postgresql
before_script:
  - psql -c 'create database travis_ci_test;' -U postgres
  - cp -f config/database.yml.travis config/database.yml
  - bundle install
  - bundle exec rake db:migrate
  - bundle exec rake db:test:prepare
script: 
  - bundle exec rspec