language: ruby
rvm:
  - 2.3.1
services:
  - postgresql
before_script:
  - psql -c "CREATE USER vagrant;" -U postgres
  - bundle install
  - bundle exec rake db:create db:migrate
  - bundle exec rake db:test:prepare
script: 
  - bundle exec rspec